#!/usr/bin/env python3
"""
Generate simulator validation table from existing phase_model_validation CSVs.
Produces both a human-readable summary and a LaTeX table for the paper.

Data sources (written by model_fitting_runner.py during the per-pool refit):
  artifacts/paper/models/models_l40s/phase_model_validation.csv
  artifacts/paper/models/models_l4/phase_model_validation.csv
"""
import sys, os
import pandas as pd

sys.path.insert(0, os.path.dirname(__file__))

ROOT = os.path.join(os.path.dirname(__file__), "..", "..")
MODEL_DIR = os.path.join(ROOT, "artifacts", "paper", "models")
L40S_CSV = os.path.join(MODEL_DIR, "models_l40s", "phase_model_validation.csv")
L4_CSV   = os.path.join(MODEL_DIR, "models_l4",   "phase_model_validation.csv")
OUT_DIR  = os.path.join(ROOT, "results", "paper", "analyses")
PAPER_DIR = os.path.join(os.path.dirname(__file__), "..")  # paper/ , \input'd by models.tex
os.makedirs(OUT_DIR, exist_ok=True)


def load_csv(path, gpu_label):
    df = pd.read_csv(path)
    df["gpu"] = gpu_label
    return df


def fmt_mape(v):
    if pd.isna(v):
        return "—"
    return f"{v:.1f}\\%"


def fmt_r2(v):
    if pd.isna(v):
        return "—"
    return f"{v:.3f}"


def fmt_prec(v):
    if pd.isna(v):
        return "—"
    return f"{v:.1f}\\%"


def fmt_false_safe(v):
    if pd.isna(v):
        return "—"
    return str(int(v))


def build_regression_block(df, gpu):
    """Return rows for TTFT and power regression metrics."""
    rows = []
    for phase, metric, label in [
        ("prefill", "latency",  "P99 TTFT"),
        ("decode",  "latency",  "P99 TPOT"),
        ("prefill", "power",    "Prefill power/GPU"),
        ("decode",  "power",    "Decode power/GPU"),
    ]:
        sel = df[(df["gpu"] == gpu) & (df["phase"] == phase) & (df["metric_type"] == metric)]
        if sel.empty:
            rows.append({"gpu": gpu, "metric": label, "n": "—",
                         "mape": "—", "r2": "—", "spearman": "—"})
            continue
        row = sel.iloc[0]
        n   = int(row["n_rows"]) if not pd.isna(row["n_rows"]) else "—"
        rows.append({
            "gpu": gpu,
            "metric": label,
            "n": n,
            "mape":     fmt_mape(row.get("cv_mape_pct")),
            "r2":       fmt_r2(row.get("cv_r2")),
            "spearman": f"{row['spearman_r']:.3f}" if not pd.isna(row.get("spearman_r", float("nan"))) else "—",
        })
    return rows


def build_feasibility_block(df, gpu):
    """Return rows for feasibility classifier metrics per SLO."""
    rows = []
    slos = sorted(df[df["metric_type"] == "feasibility"]["slo_ms"].dropna().unique())
    for slo in slos:
        for phase in ("prefill", "decode"):
            sel = df[(df["gpu"] == gpu) & (df["phase"] == phase) &
                     (df["metric_type"] == "feasibility") & (df["slo_ms"] == slo)]
            if sel.empty:
                continue
            row = sel.iloc[0]
            rows.append({
                "gpu": gpu,
                "phase": phase.capitalize(),
                "slo_ms": int(slo),
                "false_safe": fmt_false_safe(row.get("false_safe")),
                "false_safe_rate": fmt_prec(row.get("false_safe_rate_pct")),
                "precision": fmt_prec(row.get("safe_precision_pct")),
                "admit_rate": fmt_prec(row.get("admit_rate_pct")),
            })
    return rows


def print_human_readable(reg_rows, feas_rows):
    print("=" * 70)
    print("REGRESSION METRICS (cross-validated on hardware measurements)")
    print("=" * 70)
    print(f"{'GPU':<8} {'Metric':<24} {'N':>5} {'MAPE':>8} {'R²':>7} {'Spearman':>9}")
    print("-" * 70)
    for r in reg_rows:
        print(f"{r['gpu']:<8} {r['metric']:<24} {str(r['n']):>5} "
              f"{r['mape']:>8} {r['r2']:>7} {r['spearman']:>9}")

    print()
    print("=" * 70)
    print("FEASIBILITY CLASSIFIER (per GPU type, phase, SLO)")
    print("=" * 70)
    print(f"{'GPU':<8} {'Phase':<10} {'SLO':>6} {'FalseSafe':>10} {'FS%':>7} {'Precision':>10} {'AdmitRate':>10}")
    print("-" * 70)
    for r in feas_rows:
        print(f"{r['gpu']:<8} {r['phase']:<10} {r['slo_ms']:>6} "
              f"{r['false_safe']:>10} {r['false_safe_rate']:>7} "
              f"{r['precision']:>10} {r['admit_rate']:>10}")


def write_latex(reg_rows, feas_rows, out_path):
    lines = []
    lines.append(r"% Auto-generated by generate_validation_table.py")
    lines.append(r"% Regression metrics (cross-validated on real hardware)")
    lines.append(r"\begin{table}[t]")
    lines.append(r"\centering")
    lines.append(r"\caption{Phase model accuracy on real L40S and L4 hardware measurements, "
                 r"under grouped cross-validation. "
                 r"Power prediction is accurate (MAPE 6--8\%, $R^2$ 0.87--0.94). "
                 r"Latency MAPE is higher (16--25\%), but Spearman rank correlation is strong (0.94--0.97), "
                 r"so the models rank configurations reliably even when absolute predictions are imprecise. "
                 r"This suffices for the scheduler, which uses latency only for relative ranking among "
                 r"configurations already admitted by the feasibility classifier.}")
    lines.append(r"\label{tab:model_validation}")
    lines.append(r"\small")
    lines.append(r"\begin{tabular}{llrrrrr}")
    lines.append(r"\toprule")
    lines.append(r"GPU & Metric & $N$ & MAPE & $R^2$ & Spearman \\")
    lines.append(r"\midrule")
    cur_gpu = None
    for r in reg_rows:
        if r["gpu"] != cur_gpu:
            if cur_gpu is not None:
                lines.append(r"\midrule")
            cur_gpu = r["gpu"]
            lines.append(rf"\multirow{{4}}{{*}}{{{r['gpu']}}} & {r['metric']} & {r['n']} & {r['mape']} & {r['r2']} & {r['spearman']} \\")
        else:
            lines.append(rf"  & {r['metric']} & {r['n']} & {r['mape']} & {r['r2']} & {r['spearman']} \\")
    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")
    lines.append(r"\end{table}")
    lines.append("")

    # Feasibility table
    lines.append(r"% Feasibility classifier (safety-critical)")
    lines.append(r"\begin{table}[t]")
    lines.append(r"\centering")
    lines.append(r"\caption{Feasibility classifier safety metrics. "
                 r"False-safe = configurations admitted (predicted safe) that actually violate the SLO. "
                 r"The classifier is calibrated to minimize false-safe admissions first; "
                 r"the high false-safe rates (FS\%) at loose SLOs reflect very few violating "
                 r"configurations in that regime (small denominators), not many unsafe admissions. "
                 r"False-unsafe rate reflects conservative guard bands that sacrifice "
                 r"throughput for safety, and the per-window utilization gate $\rho_{\mathrm{cap}}$ "
                 r"provides an additional layer against marginal admissions.}")
    lines.append(r"\label{tab:feasibility_classifier}")
    lines.append(r"\small")
    lines.append(r"\begin{tabular}{llrrrr}")
    lines.append(r"\toprule")
    lines.append(r"GPU & Phase & SLO (ms) & False-safe & FS\% & Precision \\")
    lines.append(r"\midrule")
    cur_gpu = None
    for r in feas_rows:
        first = r["gpu"] != cur_gpu
        if first:
            if cur_gpu is not None:
                lines.append(r"\midrule")
            cur_gpu = r["gpu"]
        gpu_cell = r["gpu"] if first else ""
        lines.append(rf"  {gpu_cell} & {r['phase']} & "
                     rf"{r['slo_ms']} & {r['false_safe']} & {r['false_safe_rate']} & {r['precision']} \\")
    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")
    lines.append(r"\end{table}")

    with open(out_path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"\nLaTeX written to {out_path}")


def main():
    l40s = load_csv(L40S_CSV, "L40S")
    l4   = load_csv(L4_CSV,   "L4")
    df   = pd.concat([l40s, l4], ignore_index=True)

    reg_rows  = build_regression_block(df, "L40S") + build_regression_block(df, "L4")
    feas_rows = build_feasibility_block(df, "L40S") + build_feasibility_block(df, "L4")

    print_human_readable(reg_rows, feas_rows)

    # Save summary CSV
    pd.DataFrame(reg_rows).to_csv(os.path.join(OUT_DIR, "validation_regression.csv"), index=False)
    pd.DataFrame(feas_rows).to_csv(os.path.join(OUT_DIR, "validation_feasibility.csv"), index=False)
    print(f"\nCSVs written to {OUT_DIR}/")

    write_latex(reg_rows, feas_rows, os.path.join(OUT_DIR, "validation_tables.tex"))
    write_latex(reg_rows, feas_rows, os.path.join(PAPER_DIR, "validation_tables.tex"))


if __name__ == "__main__":
    main()
